Disable the getThumbnail call since it's raising exception and killing the process when not available. Would be good to NOT raise an exception and simply return nil.
[WARNING] Failed to get thumbnail (clip id: 56, track_id: 5): Traceback (most recent call last):
   File "/home/pi/.venv/classifier/lib/python3.11/site-packages/dbus/service.py", line 712, in _message_cb
     retval = candidate_method(self, *args, **keywords)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/home/pi/.venv/classifier/lib/python3.11/site-packages/piclassifier/service.py", line 120, in GetThumbnail
     raise Exception("No thumbnail")
 Exception: No thumbnail